version: '3.8'

services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - '5432:5432'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data