python k_means.py --save_summary --month 1
python k_means.py --save_summary --month 2
python k_means.py --save_summary --month 3
python k_means.py --save_summary --month 4
python k_means.py --save_summary --month 5
python k_means.py --save_summary --month 6
python k_means.py --save_summary --month 7
python k_means.py --save_summary --month 8
python k_means.py --save_summary --month 9
python k_means.py --save_summary --month 10
python k_means.py --save_summary --month 11
python k_means.py --save_summary --month 12